<script lang="ts">
	import Select from '$lib/Select.svelte';
	import '../app.css';
	import { createDialog, createLabel, melt } from '@melt-ui/svelte';
	import searchTerm from '$lib/search';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { Icon, InformationCircle, MagnifyingGlass, Moon, Sun, XMark } from 'svelte-hero-icons';
	import { fade } from 'svelte/transition';
	let body: HTMLBodyElement | null;
	let darkMode = true;

	const bindBody = (node: any) => (body = node);

	$: darkMode && body ? body.classList.add('dark') : body?.classList.remove('dark');
	const {
		elements: { root }
	} = createLabel();

	const arches = {
		x86: ['x86-32', 'x86-64', 'x86-x32'],
		arm: ['arm-eabi', 'arm-oabi', 'arm64-generic']
	};

	const versions = {
		v5: ['latest']
	};

	const {
		elements: { trigger, overlay, content, title, description, close, portalled },
		states: { open }
	} = createDialog();
</script>

<svelte:body use:bindBody />

<div class="min-h-screen transition-colors dark:text-neutral-100 dark:bg-black">
	<header class="mx-8">
		<nav class="mb-4">
			<div class="flex flex-row justify-between pt-8">
				<h1 class="text-lg font-bold">syscalls</h1>
				<div>
					<button use:melt={$trigger}>
						<Icon src={InformationCircle} class="w-6 h-6" />
					</button>
					<button on:click={() => (darkMode = !darkMode)}>
						<Icon src={darkMode ? Sun : Moon} class="w-6 h-6" />
					</button>
				</div>
			</div>
			<div class="grid grid-cols-5 gap-2 mt-8">
				<Select
					labelText="Arch"
					options={arches}
					defaultVal={new URL($page.url).pathname.substring(1) || 'x86-64'}
					onValueChange={({ next }) => {
						goto(`/${next}`, { invalidateAll: true, noScroll: true });
						return next;
					}}
				/>
				<Select labelText="Version" options={versions} defaultVal="latest" />
				<div />
				<div class="flex flex-col col-span-2 gap-1">
					<label
						use:melt={$root}
						for="search"
						class="block text-sm font-medium text-right text-slate-600 dark:text-slate-400"
						data-melt-part="root"
					>
						<span>Search</span>
					</label>
					<div class="grid justify-start w-full grid-cols-1 align-center">
						<input
							bind:value={$searchTerm}
							type="search"
							id="search"
							class="w-full h-10 col-start-1 row-start-1 px-3 py-2 pl-8 bg-white border rounded-md text-slate-700 dark:bg-black dark:text-slate-300 border-slate-300 dark:border-neutral-700 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
							placeholder="Search"
						/>
						<Icon
							src={MagnifyingGlass}
							class="w-5 h-5 col-start-1 row-start-1 my-auto ml-2 text-slate-400 dark:text-neutral-400"
						/>
					</div>
				</div>
			</div>
		</nav>
		<div use:melt={$portalled}>
			{#if $open}
				<div use:melt={$overlay} class="fixed inset-0 z-50 bg-black/20 dark:bg-white/20" />
				<div
					class="fixed left-[50%] top-[50%] z-50 max-h-[85vh] w-[90vw]
            max-w-[450px] translate-x-[-50%] translate-y-[-50%] rounded-lg bg-white dark:bg-black
            p-6"
					transition:fade={{
						duration: 150
					}}
					use:melt={$content}
				>
					<h2 use:melt={$title} class="m-0 text-lg font-bold dark:text-white">syscalls</h2>
					<p
						use:melt={$description}
						class="mt-2 mb-5 leading-normal text-zinc-600 dark:text-neutral-500"
					>
						syscalls is an autogenerated syscall table for linux. It parses the linux source and
						extracts syscalls into a json format which this website uses.
					</p>
					<h3 class="font-medium dark:text-white">Tips</h3>
					<ul class="list-disc list-inside text-zinc-600 dark:text-neutral-500">
						<li>
							Holding
							<span class="px-1.5 py-0.5 text-sm rounded-sm bg-slate-100 dark:bg-neutral-900">
								Enter
							</span>
							will swap
							<span class="px-1.5 py-0.5 text-sm rounded-sm bg-slate-100 dark:bg-neutral-900">
								nr
							</span> between hex and decimal
						</li>
						<li>
							<span class="px-1.5 py-0.5 text-sm rounded-sm bg-slate-100 dark:bg-neutral-900">
								nr
							</span> 1024 or greater will be displayed as hex instead of decimal, but this can be swapped
							using the above
						</li>
					</ul>
					<button
						use:melt={$close}
						aria-label="close"
						class="absolute inline-flex items-center justify-center w-6 h-6 p-1 rounded-full appearance-none right-4 top-4 hover:bg-slate-100 focus:shadow-slate-400 dark:hover:bg-neutral-800 dark:focus:shadow-neutral-500"
					>
						<Icon src={XMark} class="w-4 h-4 dark:text-white" />
					</button>
				</div>
			{/if}
		</div>
	</header>
	<main>
		<slot />
	</main>
	<footer class="pt-16" />
</div>

<style lang="postcss">
	:global(html) {
		font-family: 'JetBrains Mono';
	}
</style>
